dev: true

database:
  db_name: "dbname"
  username: "dbuser"
  password: "password"
  address: "localhost:3306"

server:
  port: "8888"
  allow_origins:
    - "localhost:8080"
  log_file_path: "./se.log"
  domain: "example.com"
  api_route: "/api"
  default_password: "password"

jwt:
  issuer: "issuer"
  secret: "secret"
  expires: 24
